# This yml file should be located in .github/workflows

name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          postmanApiKey: ${{ secrets.postmanApiKey }}
          collection: Sales Opportunities.postman_collection
          environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b
